/* Generated By:JavaCC: Do not edit this line. DriftConfigParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DriftConfigParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MONITOR = 7;
  /** RegularExpression Id. */
  int SOURCE = 8;
  /** RegularExpression Id. */
  int BASELINE = 9;
  /** RegularExpression Id. */
  int DRIFT_CHECK = 10;
  /** RegularExpression Id. */
  int EVERY = 11;
  /** RegularExpression Id. */
  int METHOD = 12;
  /** RegularExpression Id. */
  int THRESHOLD = 13;
  /** RegularExpression Id. */
  int ALERT = 14;
  /** RegularExpression Id. */
  int SEVERITY = 15;
  /** RegularExpression Id. */
  int FEATURE_DRIFT = 16;
  /** RegularExpression Id. */
  int ON = 17;
  /** RegularExpression Id. */
  int SIGNIFICANCE = 18;
  /** RegularExpression Id. */
  int METADATA = 19;
  /** RegularExpression Id. */
  int OWNER = 20;
  /** RegularExpression Id. */
  int VERSION = 21;
  /** RegularExpression Id. */
  int DESCRIPTION = 22;
  /** RegularExpression Id. */
  int TIME_UNIT = 23;
  /** RegularExpression Id. */
  int LBRACE = 24;
  /** RegularExpression Id. */
  int RBRACE = 25;
  /** RegularExpression Id. */
  int COLON = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int LBRACKET = 28;
  /** RegularExpression Id. */
  int RBRACKET = 29;
  /** RegularExpression Id. */
  int UNDERSCORE = 30;
  /** RegularExpression Id. */
  int NUMBER = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int STRING_LITERAL = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"monitor\"",
    "\"source\"",
    "\"baseline\"",
    "\"drift_check\"",
    "\"every\"",
    "\"method\"",
    "\"threshold\"",
    "\"alert\"",
    "\"severity\"",
    "\"feature_drift\"",
    "\"on\"",
    "\"significance\"",
    "\"metadata\"",
    "\"owner\"",
    "\"version\"",
    "\"description\"",
    "<TIME_UNIT>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"_\"",
    "<NUMBER>",
    "<FLOAT>",
    "<IDENTIFIER>",
    "<STRING_LITERAL>",
  };

}
