package main;

import ast.*;
import java.util.List;
import java.io.PrintWriter;

public class PythonGenerator {

    public void generate(List<MonitorConfig> configs, String outputFilePath) {
        try (PrintWriter out = new PrintWriter(outputFilePath)) {
            
            // Add imports and a short header to the generated Python file
            writeHeader(out);

            // 2. Generate Configuration Dictionary
            out.println("\n# --- Generated Configuration from DSL ---");
            out.println("MONITORS = [");
            
            for (MonitorConfig m : configs) {
                out.println("    {");
                out.println("        'name': '" + m.monitorName + "',");
                out.println("        'source': '" + m.source + "',");
                out.println("        'baseline': '" + m.baseline + "',");
                
                // Drift check configuration
                out.println("        'drift_check': {");
                out.println("            'method': '" + m.driftCheck.method + "',");
                out.println("            'threshold': " + m.driftCheck.threshold + ",");
                out.println("            'interval_sec': " + toSeconds(m.driftCheck.intervalNumber, m.driftCheck.intervalUnit) + ",");
                out.println("            'alerts': " + listToPy(m.driftCheck.alertChannels));
                out.println("        },");

                // Feature drift (optional)
                if (m.featureDrift != null) {
                    out.println("        'feature_drift': {");
                    out.println("            'features': " + listToPy(m.featureDrift.features) + ",");
                    out.println("            'method': '" + m.featureDrift.method + "',");
                    out.println("            'significance': " + m.featureDrift.significance);
                    out.println("        },");
                }
                
                out.println("    },");
            }
            out.println("]");

            // Write runtime helper code for the generated script
            writeRuntime(out);

            System.out.println("-> Generated Python Script: " + outputFilePath);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void writeHeader(PrintWriter out) {
        out.println("#!/usr/bin/env python3");
        out.println("import time");
        out.println("import random");
        out.println("");
        out.println("# This file was auto-generated by the DriftDSL Compiler");
        out.println("# It configures and runs drift detection checks.");
        out.println("# ----------------------------------------");
    }

    private void writeRuntime(PrintWriter out) {
        out.println("");
        out.println("# --- Runtime Execution Logic ---");
        out.println("def check_drift(monitor):");
        out.println("    print(f\"\\n[Starting] Monitor: {monitor['name']}\")");
        out.println("    print(f\"  Source: {monitor['source']} vs Baseline: {monitor['baseline']}\")");
        out.println("");
        out.println("    # 1. Check Embedding Drift");
        out.println("    dc = monitor['drift_check']");
        out.println("    # Simulate a drift score (random value for demo purposes)");
        out.println("    detected_score = round(random.uniform(0.0, 0.5), 3)");
        out.println("    print(f\"  Checking {dc['method']}... Score: {detected_score} (Threshold: {dc['threshold']})\")");
        out.println("");
        out.println("    if detected_score > dc['threshold']:");
        out.println("        print(f\"  !!! ALERT !!! Drift detected. Sending to {dc['alerts']}\")");
        out.println("    else:");
        out.println("        print(\"  Status: OK\")");
        out.println("");
        out.println("    # 2. Check Feature Drift (if configured)");
        out.println("    if 'feature_drift' in monitor:");
        out.println("        fd = monitor['feature_drift']");
        out.println("        print(f\"  Checking features {fd['features']} using {fd['method']}...\")");
        out.println("");
        out.println("if __name__ == '__main__':");
        out.println("    print(\"DriftDSL Runtime Loaded.\")");
        out.println("    for m in MONITORS:");
        out.println("        check_drift(m)");
    }

    // Helper: Convert units to seconds
    private int toSeconds(int num, String unit) {
        switch (unit) {
            case "minutes": return num * 60;
            case "hours":   return num * 3600;
            case "daily":   return num * 86400;
            case "weekly":  return num * 604800; // Added support for weekly
            case "monthly": return num * 2592000; // Approx 30 days
            default: return num;
        }
    }

    // Helper: Convert Java List to Python List format
    private String listToPy(List<String> list) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < list.size(); i++) {
            sb.append("'" + list.get(i) + "'");
            if (i < list.size() - 1) sb.append(", ");
        }
        sb.append("]");
        return sb.toString();
    }
}